package integrator

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// TestIntegrator integrates generated tests into existing test suites
type TestIntegrator struct {
	projectRoot string
}

// NewTestIntegrator creates a new test integrator
func NewTestIntegrator(projectRoot string) *TestIntegrator {
	return &TestIntegrator{
		projectRoot: projectRoot,
	}
}

// IntegrationResult represents the result of test integration
type IntegrationResult struct {
	FilesIntegrated   int      `json:"files_integrated"`
	TestsAdded        int      `json:"tests_added"`
	DuplicatesSkipped int      `json:"duplicates_skipped"`
	Errors            []string `json:"errors,omitempty"`
}

// IntegrateUnitTests integrates unit tests into the project test directory
func (ti *TestIntegrator) IntegrateUnitTests(testDir, targetDir string) (*IntegrationResult, error) {
	fmt.Println("🔗 Integrating unit tests into existing test suite...")

	result := &IntegrationResult{
		FilesIntegrated:   0,
		TestsAdded:        0,
		DuplicatesSkipped: 0,
		Errors:            []string{},
	}

	// Create target directory if it doesn't exist
	if err := os.MkdirAll(targetDir, 0755); err != nil {
		return nil, fmt.Errorf("failed to create target directory: %w", err)
	}

	// Walk through generated test directory
	err := filepath.Walk(testDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		// Skip directories
		if info.IsDir() {
			return nil
		}

		// Only process test files
		if !ti.isTestFile(path) {
			return nil
		}

		// Get relative path
		relPath, err := filepath.Rel(testDir, path)
		if err != nil {
			result.Errors = append(result.Errors, fmt.Sprintf("Failed to get relative path for %s: %v", path, err))
			return nil
		}

		// Determine target path
		targetPath := filepath.Join(targetDir, relPath)

		// Check if test already exists
		if ti.testExists(targetPath, path) {
			result.DuplicatesSkipped++
			fmt.Printf("⏭️  Skipping duplicate test: %s\n", relPath)
			return nil
		}

		// Copy or merge test file
		if err := ti.integrateTestFile(path, targetPath); err != nil {
			result.Errors = append(result.Errors, fmt.Sprintf("Failed to integrate %s: %v", relPath, err))
			return nil
		}

		result.FilesIntegrated++
		fmt.Printf("✅ Integrated: %s\n", relPath)

		return nil
	})

	if err != nil {
		return nil, fmt.Errorf("failed to walk test directory: %w", err)
	}

	fmt.Printf("✅ Integration complete: %d files integrated, %d duplicates skipped\n",
		result.FilesIntegrated, result.DuplicatesSkipped)

	return result, nil
}

// CommitTests commits the integrated tests to the current branch
func (ti *TestIntegrator) CommitTests(targetDir, branch, commit string) error {
	fmt.Println("📝 Committing generated tests to PR...")

	// Check if there are changes to commit
	cmd := exec.Command("git", "status", "--porcelain", targetDir)
	cmd.Dir = ti.projectRoot
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("failed to check git status: %w", err)
	}

	if len(output) == 0 {
		fmt.Println("ℹ️  No new tests to commit")
		return nil
	}

	// Configure git user
	if err := ti.configureGitUser(); err != nil {
		return err
	}

	// Add files
	cmd = exec.Command("git", "add", targetDir)
	cmd.Dir = ti.projectRoot
	if output, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("failed to add files: %w\n%s", err, output)
	}

	// Commit
	commitMsg := fmt.Sprintf(`🤖 Add AI-generated unit tests

Generated by Intelligent Test Orchestrator
Commit: %s
Branch: %s

This commit adds automatically generated unit tests based on code changes detected in this PR.`, commit, branch)

	cmd = exec.Command("git", "commit", "-m", commitMsg)
	cmd.Dir = ti.projectRoot
	if output, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("failed to commit: %w\n%s", err, output)
	}

	// Push to branch
	cmd = exec.Command("git", "push", "origin", branch)
	cmd.Dir = ti.projectRoot
	if output, err := cmd.CombinedOutput(); err != nil {
		fmt.Printf("⚠️  Could not push to branch: %v\n%s", err, output)
		// Non-fatal error
	} else {
		fmt.Println("✅ Tests committed and pushed successfully")
	}

	return nil
}

// isTestFile checks if a file is a test file
func (ti *TestIntegrator) isTestFile(path string) bool {
	name := filepath.Base(path)
	return strings.HasSuffix(name, "_test.go") ||
		strings.HasPrefix(name, "test_") ||
		strings.Contains(name, ".test.")
}

// testExists checks if a test already exists
func (ti *TestIntegrator) testExists(targetPath, sourcePath string) bool {
	// Check if target file exists
	if _, err := os.Stat(targetPath); os.IsNotExist(err) {
		return false
	}

	// Read both files and compare content
	sourceContent, err := os.ReadFile(sourcePath)
	if err != nil {
		return false
	}

	targetContent, err := os.ReadFile(targetPath)
	if err != nil {
		return false
	}

	// Simple duplicate detection: check if content is similar
	// In a production system, this would use more sophisticated comparison
	sourceStr := string(sourceContent)
	targetStr := string(targetContent)

	// Check if the test functions already exist in target
	return ti.containsSimilarTests(sourceStr, targetStr)
}

// containsSimilarTests checks if similar tests exist
func (ti *TestIntegrator) containsSimilarTests(source, target string) bool {
	// Extract test function names from source
	sourceTests := ti.extractTestNames(source)

	// Check if any of these tests exist in target
	for _, testName := range sourceTests {
		if strings.Contains(target, testName) {
			return true
		}
	}

	return false
}

// extractTestNames extracts test function names from code
func (ti *TestIntegrator) extractTestNames(code string) []string {
	names := []string{}
	lines := strings.Split(code, "\n")

	for _, line := range lines {
		line = strings.TrimSpace(line)
		// Go test pattern
		if strings.HasPrefix(line, "func Test") {
			parts := strings.Fields(line)
			if len(parts) >= 2 {
				name := strings.TrimSuffix(parts[1], "(t")
				name = strings.TrimSuffix(name, "(")
				names = append(names, name)
			}
		}
		// Python test pattern
		if strings.HasPrefix(line, "def test_") {
			parts := strings.Fields(line)
			if len(parts) >= 2 {
				name := strings.TrimSuffix(parts[1], "():")
				name = strings.TrimSuffix(name, ":")
				names = append(names, name)
			}
		}
	}

	return names
}

// integrateTestFile integrates a test file into the target location
func (ti *TestIntegrator) integrateTestFile(sourcePath, targetPath string) error {
	// Create target directory if needed
	targetDir := filepath.Dir(targetPath)
	if err := os.MkdirAll(targetDir, 0755); err != nil {
		return fmt.Errorf("failed to create target directory: %w", err)
	}

	// If target doesn't exist, simply copy
	if _, err := os.Stat(targetPath); os.IsNotExist(err) {
		return ti.copyFile(sourcePath, targetPath)
	}

	// If target exists, merge the tests
	return ti.mergeTestFiles(sourcePath, targetPath)
}

// copyFile copies a file from source to target
func (ti *TestIntegrator) copyFile(source, target string) error {
	input, err := os.ReadFile(source)
	if err != nil {
		return err
	}

	return os.WriteFile(target, input, 0644)
}

// mergeTestFiles merges source test file into target test file
func (ti *TestIntegrator) mergeTestFiles(source, target string) error {
	// Read both files
	sourceContent, err := os.ReadFile(source)
	if err != nil {
		return err
	}

	targetContent, err := os.ReadFile(target)
	if err != nil {
		return err
	}

	// Extract new tests from source that don't exist in target
	newTests := ti.extractNewTests(string(sourceContent), string(targetContent))

	if len(newTests) == 0 {
		return nil // No new tests to add
	}

	// Append new tests to target file
	file, err := os.OpenFile(target, os.O_APPEND|os.O_WRONLY, 0644)
	if err != nil {
		return err
	}
	defer file.Close()

	// Add separator comment
	if _, err := file.WriteString("\n// Auto-generated tests added by AI Test Orchestrator\n\n"); err != nil {
		return err
	}

	// Write new tests
	for _, test := range newTests {
		if _, err := file.WriteString(test + "\n\n"); err != nil {
			return err
		}
	}

	return nil
}

// extractNewTests extracts tests from source that don't exist in target
func (ti *TestIntegrator) extractNewTests(source, target string) []string {
	newTests := []string{}
	currentTest := ""
	inTest := false

	lines := strings.Split(source, "\n")

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)

		// Check if this is the start of a test function
		if strings.HasPrefix(trimmed, "func Test") || strings.HasPrefix(trimmed, "def test_") {
			// Save previous test if any
			if inTest && currentTest != "" {
				testName := ti.extractTestNameFromCode(currentTest)
				if testName != "" && !strings.Contains(target, testName) {
					newTests = append(newTests, currentTest)
				}
			}
			// Start new test
			currentTest = line + "\n"
			inTest = true
		} else if inTest {
			currentTest += line + "\n"
			// Check if test function ended (simple heuristic)
			if trimmed == "}" || (trimmed == "" && strings.HasPrefix(strings.TrimSpace(currentTest), "def test_")) {
				testName := ti.extractTestNameFromCode(currentTest)
				if testName != "" && !strings.Contains(target, testName) {
					newTests = append(newTests, currentTest)
				}
				currentTest = ""
				inTest = false
			}
		}
	}

	// Handle last test
	if inTest && currentTest != "" {
		testName := ti.extractTestNameFromCode(currentTest)
		if testName != "" && !strings.Contains(target, testName) {
			newTests = append(newTests, currentTest)
		}
	}

	return newTests
}

// extractTestNameFromCode extracts the test function name from code
func (ti *TestIntegrator) extractTestNameFromCode(code string) string {
	lines := strings.Split(code, "\n")
	if len(lines) == 0 {
		return ""
	}

	firstLine := strings.TrimSpace(lines[0])

	// Go pattern
	if strings.HasPrefix(firstLine, "func Test") {
		parts := strings.Fields(firstLine)
		if len(parts) >= 2 {
			return strings.TrimSuffix(parts[1], "(t")
		}
	}

	// Python pattern
	if strings.HasPrefix(firstLine, "def test_") {
		parts := strings.Fields(firstLine)
		if len(parts) >= 2 {
			return strings.TrimSuffix(parts[1], "():")
		}
	}

	return ""
}

// configureGitUser configures git user for commits
func (ti *TestIntegrator) configureGitUser() error {
	// Set user name
	cmd := exec.Command("git", "config", "user.name", "AI Test Orchestrator")
	cmd.Dir = ti.projectRoot
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("failed to set git user name: %w", err)
	}

	// Set user email
	cmd = exec.Command("git", "config", "user.email", "test-orchestrator@ibm.com")
	cmd.Dir = ti.projectRoot
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("failed to set git user email: %w", err)
	}

	return nil
}

// Made with Bob
